### ISSUE TITLE
Do we allow one actor to own more than one custom capabilities?

### ISSUE THREAD

**Issue by kevingzhang** [waxosuit/wascap#14]
Current CLI has a "-c" but only one custom capability is allowed? Is it by design?

**Comment by autodidaddict** [comment]
Just repeat the -c parameter. Actors have no limit on well known or custom
capabilities. There are a number of signed samples with two custom
capabilities.

**Comment by kevingzhang** [comment]
This is the error message I got.

wascap sign target/wasm32-wasi/debug/tea_ra.wasm target/wasm32-wasi/debug/tea_ra_signed.wasm -i .keys/account.nk -u .keys/module.nk -p -c tea:ra -c tea:tpm -n "TEA project: TPM Simulator Capability Provider"
Command line failure: Capability providers cannot provide multiple capabilities at once.

**Comment by autodidaddict** [comment]
Take away the -p. You can either have an actor that consumes multiple
capabilities or a portable provider (what that -p flag indicates) that
exposes a single capability.

**Comment by kevingzhang** [comment]
Yeah, I noticed that. I was trying to make a provider + actor at the beginning. I realized that it is not possible. I can either make a provider with a single cap or an actor with multiple caps. 
Well, thank you for your response. I will close it now.
