### ISSUE TITLE
Add the `call_alias` field to Actor metadata

### ISSUE THREAD

**Issue by autodidaddict** [waxosuit/wascap#31]
Actor metadata needs to have an `Option<String>` field called `call_alias` that , as the name implies, holds an alias that can be used to invoke this actor instead of an OCI reference or its public key. The alias must be forced to be all lowercase, all snake case, contain no spaces or odd characters.

**Comment by brooksmtownsend** [comment]
No idea when we did this but this is 10000% done 😆
