### ISSUE TITLE
Move this repository under the crates subdirectory of wasmCloud

### ISSUE THREAD

**Issue by brooksmtownsend** [waxosuit/wascap#34]
`wascap` is primarily used by wasmCloud, and in the interest of consolidating our crates and repositories it should be relocated to the `crates/` subdirectory of the [wasmCloud](https://github.com/wasmCloud/wasmCloud) repo.

**Comment by brooksmtownsend** [comment]
This can be done in such a way that preserves git history, and we should do that by merging the two histories of `wascap` and wasmcloud.

**Comment by connorsmith256** [comment]
Resolved by https://github.com/wasmCloud/wasmCloud/pull/762
