### ISSUE TITLE
unmaintained dependency flagged by cargo-audit: RUSTSEC-2022-0061 

### ISSUE THREAD

**Issue by stevelr** [waxosuit/wascap#38]
any downstream crate that depends on wascap 0.8.0 will get a warning from cargo-audit because a dependency, `parity-wasm` is marked unmaintained.

```
Crate:     parity-wasm
Version:   0.42.2
Warning:   unmaintained
Title:     Crate `parity-wasm` deprecated by the author
Date:      2022-10-01
ID:        RUSTSEC-2022-0061
URL:       https://rustsec.org/advisories/RUSTSEC-2022-0061
Dependency tree:
parity-wasm 0.42.2
└── wascap 0.8.0
```

The [wasmparser](https://crates.io/crates/wasmparser} crate maintained by BytecodeAlliance has some related functionality and could be investigated as a replacement.

**Comment by ricochet** [comment]
Fixed by #39
